services:
  # redis:
  #   image: redislabs/redismod
  #   ports:
  #     - '6379:6379'
  web:
    build:
      context: .
      target: builder
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    links:
      - db
      # - redis
    depends_on:
      - db
      # - redis

  db:
    image: postgres:14.0-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: my_random_app

    # depends_on:
    #   - redis
