"""empty message

Revision ID: 75a4153e1f09
Revises: 4e253f976415
Create Date: 2023-05-06 07:08:44.334981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75a4153e1f09'
down_revision = '4e253f976415'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        """ First, set nullable True """
        batch_op.add_column(sa.Column('created_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.Integer(), nullable=True))

    """ Second, set default value to column, then set nullable=False """
    op.execute("UPDATE users SET created_at = 0 WHERE created_at IS NULL")
    op.alter_column('users', 'created_at', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
